/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.github.thiagodutra;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.awt.*;

import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.*;


/**
 *
 * @author tdutra
 */
public class Screen extends javax.swing.JFrame {

    private MyPanel area;

    private static final Logger logger = LoggerFactory.getLogger(Screen.class);

    ButtonOptions option = ButtonOptions.RETA_DDA;
    boolean alreadyClicked = false;
    int x1,x2,y1,y2;
    ArrayList<Reta> screenLine = new ArrayList<>();
    
    public Screen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    private void initComponents() {
        this.area = new MyPanel();
        JMenuBar topBar = new JMenuBar();
        JMenu rectButton = new JMenu();
        JMenuItem ddaButton = new JMenuItem();
        JMenuItem bresenButton = new JMenuItem();
        JMenuItem clear = new JMenu();
        JMenuItem clearScreen = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        area.setBackground(new Color(255, 255, 255));
        area.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent evt) {
                areaMousePressed(evt);
            }
        });

        GroupLayout areaLayout = new GroupLayout(area);
        area.setLayout(areaLayout);
        areaLayout.setHorizontalGroup(
            areaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 1157, Short.MAX_VALUE)
        );
        areaLayout.setVerticalGroup(
            areaLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );

        topBar.setPreferredSize(new Dimension(435, 30));

        rectButton.setText("Retas");

        ddaButton.setText("DDA");
        ddaButton.addActionListener(this::ddaButtonActionPerformed);
        rectButton.add(ddaButton);

        bresenButton.setText("Bresenham");
        bresenButton.addActionListener(this::bresenButtonActionPerformed);
        rectButton.add(bresenButton);

        topBar.add(rectButton);

        clear.setText("Limpar");
        clear.addActionListener(this::clearActionPerformed);

        clearScreen.setText("Limpar Tela");
        clearScreen.addActionListener(this::clearScreenActionPerformed);
        clear.add(clearScreen);

        topBar.add(clear);

        setJMenuBar(topBar);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(area, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(area, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    private void ddaButtonActionPerformed(ActionEvent evt) {
        option = ButtonOptions.RETA_DDA;
    }

    private void areaMousePressed(MouseEvent evt) {
        logger.info(String.format("has been clicked = %s", alreadyClicked));
            if (!alreadyClicked) {
                alreadyClicked = true;
                x1 = evt.getX();
                y1 = evt.getY();
                logger.info(String.format("Getting X1: %d", x1));

                switch (option) {
                    case PREENCHIMENTO_BOUNDARY:
                        Reta.boundaryFill4(x1,y1, Color.BLACK.getRGB(), Color.BLACK.getRGB(), area.getBuffer());
                        area.update();
                        alreadyClicked = false;
                        break;

                    case PREENCHIMENTO_FLOOD:
                        Reta.floodFill4(x1,y1, Color.WHITE.getRGB(), Color.BLACK.getRGB(), area.getBuffer());
                        area.update();
                        alreadyClicked = false;
                        break;
                }
                
            } else {
                alreadyClicked = false;
                x2 = evt.getX();
                y2 = evt.getY();
                logger.info(String.format("Getting X2: %d", x2));

                switch (option) {
                    case RETA_DDA:
                        Reta newLine1 = new Reta(x1, y1, x2, y2);
                        screenLine.add(newLine1);
                        newLine1.dda( x1, y1, x2, y2, area.getBuffer(), Color.BLACK.getRGB() );
                        area.update();
                        break;

                    case RETA_BRESENHAM:
                        Reta newLine2 = new Reta(x1, y1, x2, y2);
                        screenLine.add(newLine2);
                        newLine2.bresenham( x1, y1, x2, y2, area.getBuffer() );
                        area.update();
                        break;
                }
            }
    }

    private void bresenButtonActionPerformed(ActionEvent evt) { option = ButtonOptions.RETA_BRESENHAM;
    }

    private void clearActionPerformed(ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        area.repaint();
    }

    private void clearScreenActionPerformed(ActionEvent evt) {
        area.repaint();
        area.clear();
        screenLine.clear();
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | UnsupportedLookAndFeelException | IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new Screen().setVisible(true));
    }
}
